plugins:
- id: ace-editor
- id: active-directory
- id: ant
- id: antisamy-markup-formatter
- id: apache-httpcomponents-client-4-api
- id: async-http-client
- id: authentication-tokens
- id: aws-credentials
- id: aws-java-sdk
- id: aws-java-sdk-ec2
- id: aws-java-sdk-minimal
- id: basic-branch-build-strategies
- id: blueocean-autofavorite
- id: blueocean-commons
- id: blueocean-config
- id: blueocean-core-js
- id: blueocean-dashboard
- id: blueocean-display-url
- id: blueocean-events
- id: blueocean-git-pipeline
- id: blueocean-github-pipeline
- id: blueocean-i18n
- id: blueocean-jwt
- id: blueocean-personalization
- id: blueocean-pipeline-api-impl
- id: blueocean-pipeline-editor
- id: blueocean-bitbucket-pipeline
- id: blueocean-pipeline-scm-api
- id: blueocean-rest-impl
- id: blueocean-rest
- id: blueocean-web
- id: blueocean
- id: bootstrap4-api
- id: bootstrap5-api
- id: bouncycastle-api
- id: branch-api
- id: build-failure-analyzer
- id: caffeine-api
- id: checks-api
- id: cloudbees-administrative-monitors
- id: cloudbees-analytics
- id: cloudbees-assurance
- id: cloudbees-bitbucket-branch-source
- id: cloudbees-blueocean-default-theme
- id: cloudbees-casc-client
- id: cloudbees-casc-items-api
- id: cloudbees-casc-items-commons
- id: cloudbees-casc-items-controller
- id: cloudbees-folder
- id: cloudbees-folders-plus
- id: cloudbees-github-reporting
- id: cloudbees-groovy-view
- id: cloudbees-jenkins-advisor
- id: cloudbees-jsync-archiver
- id: cloudbees-label-throttling-plugin
- id: cloudbees-license
- id: cloudbees-monitoring
- id: cloudbees-nodes-plus
- id: cloudbees-platform-common
- id: cloudbees-platform-data
- id: cloudbees-plugin-usage
- id: cloudbees-ssh-slaves
- id: cloudbees-support
- id: cloudbees-template
- id: cloudbees-uc-data-api
- id: cloudbees-unified-ui
- id: cloudbees-view-creation-filter
- id: cloudbees-workflow-template
- id: cloudbees-workflow-ui
- id: command-launcher
- id: configuration-as-code
- id: credentials-binding
- id: credentials
- id: display-url-api
- id: durable-task
- id: echarts-api
- id: email-ext
- id: favorite
- id: font-awesome-api
- id: gcp-secrets-manager-credentials-provider
- id: git-client
- id: git-server
- id: git-validated-merge
- id: git
- id: github-api
- id: github-branch-source
- id: github-pull-request-build
- id: github
- id: google-compute-engine
- id: google-metadata-plugin
- id: google-oauth-plugin
- id: google-storage-plugin
- id: gradle
- id: handlebars
- id: handy-uri-templates-2-api
- id: hashicorp-vault-plugin
- id: htmlpublisher
- id: infradna-backup
- id: jackson2-api
- id: jaxb
- id: jdk-tool
- id: jenkins-design-language
- id: jira
- id: jjwt-api
- id: job-dsl
- id: jquery3-api
- id: jsch
- id: junit
- id: kube-agent-management
- id: kubernetes-client-api
- id: kubernetes-credentials
- id: kubernetes
- id: ldap
- id: lockable-resources
- id: mailer
- id: mapdb-api
- id: matrix-project
- id: metrics
- id: momentjs
- id: nectar-license
- id: nectar-rbac
- id: node-iterator-api
- id: oauth-credentials
- id: okhttp-api
- id: operations-center-agent
- id: operations-center-client
- id: operations-center-cloud
- id: operations-center-context
- id: permissive-script-security
- id: pipeline-build-step
- id: pipeline-graph-analysis
- id: pipeline-input-step
- id: pipeline-milestone-step
- id: pipeline-rest-api
- id: pipeline-stage-step
- id: pipeline-stage-tags-metadata
- id: pipeline-stage-view
- id: plain-credentials
- id: plugin-util-api
- id: popper-api
- id: popper2-api
- id: pubsub-light
- id: scm-api
- id: script-security
- id: skip-plugin
- id: slack
- id: snakeyaml-api
- id: sonar
- id: splunk-devops
- id: splunk-devops-extend
- id: sse-gateway
- id: ssh-credentials
- id: ssh-slaves
- id: sshd
- id: structs
- id: support-core
- id: timestamper
- id: token-macro
- id: trilead-api
- id: unique-id
- id: user-activity-monitoring
- id: variant
- id: vsphere-cloud
- id: workflow-aggregator
- id: workflow-api
- id: workflow-basic-steps
- id: workflow-cps-checkpoint
- id: workflow-cps-global-lib
- id: workflow-cps
- id: workflow-durable-task-step
- id: workflow-job
- id: workflow-multibranch
- id: workflow-scm-step
- id: workflow-step-api
- id: workflow-support
