plugins:
- {id: ace-editor}
- {id: analysis-core}
- {id: analysis-model-api}
- {id: ansicolor}
- {id: ant}
- {id: antisamy-markup-formatter}
- {id: apache-httpcomponents-client-4-api}
- {id: artifact-manager-s3}
- {id: async-http-client}
- {id: audit-trail}
- {id: authentication-tokens}
- {id: aws-credentials}
- {id: aws-global-configuration}
- {id: aws-java-sdk}
- {id: basic-branch-build-strategies}
- {id: blueocean}
- {id: blueocean-autofavorite}
- {id: blueocean-bitbucket-pipeline}
- {id: blueocean-commons}
- {id: blueocean-config}
- {id: blueocean-core-js}
- {id: blueocean-dashboard}
- {id: blueocean-display-url}
- {id: blueocean-events}
- {id: blueocean-git-pipeline}
- {id: blueocean-github-pipeline}
- {id: blueocean-i18n}
- {id: blueocean-jira}
- {id: blueocean-jwt}
- {id: blueocean-personalization}
- {id: blueocean-pipeline-api-impl}
- {id: blueocean-pipeline-editor}
- {id: blueocean-pipeline-scm-api}
- {id: blueocean-rest}
- {id: blueocean-rest-impl}
- {id: blueocean-web}
- {id: bluesteel-master}
- {id: bootstrap4-api}
- {id: bootstrap5-api}
- {id: bouncycastle-api}
- {id: branch-api}
- {id: build-failure-analyzer}
- {id: build-name-setter}
- {id: build-timeout}
- {id: build-user-vars-plugin}
- {id: caffeine-api}
- {id: checks-api}
- {id: cloudbees-administrative-monitors}
- {id: cloudbees-analytics}
- {id: cloudbees-assurance}
- {id: cloudbees-aws-cli}
- {id: cloudbees-bitbucket-branch-source}
- {id: cloudbees-blueocean-default-theme}
- {id: cloudbees-casc-api}
- {id: cloudbees-disk-usage-simple}
- {id: cloudbees-folder}
- {id: cloudbees-folders-plus}
- {id: cloudbees-jsync-archiver}
- {id: cloudbees-license}
- {id: cloudbees-monitoring}
- {id: cloudbees-nodes-plus}
- {id: cloudbees-platform-common}
- {id: cloudbees-platform-data}
- {id: cloudbees-plugin-usage}
- {id: cloudbees-request-filter}
- {id: cloudbees-ssh-slaves}
- {id: cloudbees-support}
- {id: cloudbees-template}
- {id: cloudbees-uc-data-api}
- {id: cloudbees-unified-ui}
- {id: cloudbees-workflow-template}
- {id: command-launcher}
- {id: commons-lang3-api}
- {id: commons-text-api}
- {id: conditional-buildstep}
- {id: config-file-provider}
- {id: configuration-as-code}
- {id: configuration-as-code-groovy}
- {id: configuration-as-code-support}
- {id: countjobs-viewstabbar}
- {id: credentials}
- {id: credentials-binding}
- {id: cygpath}
- {id: data-tables-api}
- {id: display-url-api}
- {id: docker-commons}
- {id: docker-workflow}
- {id: dropdown-viewstabbar-plugin}
- {id: dtkit-api}
- {id: durable-task}
- {id: echarts-api}
- {id: email-ext}
- {id: embeddable-build-status}
- {id: envinject}
- {id: envinject-api}
- {id: extended-read-permission}
- {id: external-monitor-job}
- {id: favorite}
- {id: findbugs}
- {id: flaky-test-handler}
- {id: font-awesome-api}
- {id: forensics-api}
- {id: form-element-path}
- {id: git}
- {id: git-client}
- {id: git-server}
- {id: github}
- {id: github-api}
- {id: github-branch-source}
- {id: github-organization-folder}
- {id: google-oauth-plugin}
- {id: greenballs}
- {id: groovy-label-assignment}
- {id: h2-api}
- {id: handlebars}
- {id: handy-uri-templates-2-api}
- {id: heavy-job}
- {id: htmlpublisher}
- {id: http_request}
- {id: infradna-backup}
- {id: jackson2-api}
- {id: javadoc}
- {id: jaxb}
- {id: jdk-tool}
- {id: jenkins-design-language}
- {id: jira}
- {id: jjwt-api}
- {id: job-dsl}
- {id: jquery}
- {id: jquery-detached}
- {id: jquery3-api}
- {id: jsch}
- {id: junit}
- {id: junit-attachments}
- {id: kube-agent-management}
- {id: kubernetes}
- {id: kubernetes-cli}
- {id: kubernetes-client-api}
- {id: kubernetes-credentials}
- {id: kubernetes-credentials-provider}
- {id: ldap}
- {id: mailer}
- {id: mapdb-api}
- {id: matrix-auth}
- {id: matrix-project}
- {id: maven-plugin}
- {id: mercurial}
- {id: metrics}
- {id: momentjs}
- {id: monitoring}
- {id: multibranch-build-strategy-extension}
- {id: multiple-scms}
- {id: naginator}
- {id: nectar-license}
- {id: nectar-rbac}
- {id: next-build-number}
- {id: node-iterator-api}
- {id: nodelabelparameter}
- {id: notification-api}
- {id: oauth-credentials}
- {id: okhttp-api}
- {id: operations-center-agent}
- {id: operations-center-analytics-config}
- {id: operations-center-analytics-reporter}
- {id: operations-center-client}
- {id: operations-center-cloud}
- {id: operations-center-context}
- {id: operations-center-notification}
- {id: pam-auth}
- {id: parameterized-trigger}
- {id: pipeline-build-step}
- {id: pipeline-event-step}
- {id: pipeline-github-lib}
- {id: pipeline-graph-analysis}
- {id: pipeline-input-step}
- {id: pipeline-maven}
- {id: pipeline-milestone-step}
- {id: pipeline-model-api}
- {id: pipeline-model-declarative-agent}
- {id: pipeline-model-definition}
- {id: pipeline-model-extensions}
- {id: pipeline-rest-api}
- {id: pipeline-stage-step}
- {id: pipeline-stage-tags-metadata}
- {id: pipeline-stage-view}
- {id: pipeline-utility-steps}
- {id: plain-credentials}
- {id: plugin-util-api}
- {id: popper-api}
- {id: popper2-api}
- {id: postbuildscript}
- {id: PrioritySorter}
- {id: project-description-setter}
- {id: prometheus}
- {id: pubsub-light}
- {id: purge-build-queue-plugin}
- {id: purge-job-history}
- {id: rebuild}
- {id: resource-disposer}
- {id: run-condition}
- {id: saml}
- {id: scm-api}
- {id: script-security}
- {id: sdlc-build-notifier-advanced}
- {id: shelve-project-plugin}
- {id: simple-theme-plugin}
- {id: snakeyaml-api}
- {id: sonar}
- {id: splunk-devops}
- {id: sse-gateway}
- {id: ssh-credentials}
- {id: sshd}
- {id: structs}
- {id: support-core}
- {id: tasks}
- {id: test-results-analyzer}
- {id: throttle-concurrents}
- {id: timestamper}
- {id: token-macro}
- {id: trilead-api}
- {id: unique-id}
- {id: user-activity-monitoring}
- {id: variant}
- {id: warnings-ng}
- {id: wikitext}
- {id: windows-slaves}
- {id: workflow-aggregator}
- {id: workflow-api}
- {id: workflow-basic-steps}
- {id: workflow-cps}
- {id: workflow-cps-checkpoint}
- {id: workflow-cps-global-lib}
- {id: workflow-durable-task-step}
- {id: workflow-job}
- {id: workflow-multibranch}
- {id: workflow-scm-step}
- {id: workflow-step-api}
- {id: workflow-support}
- {id: ws-cleanup}
- {id: xunit}
